detection_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
                  path('admin/', admin.site.urls),
                  path('object_detection/', include('object_detection.urls')),
                  path('', RedirectView.as_view(url='/object_detection/', permanent=True)),
              ]
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

object_detection/urls.py
from django.urls import path
from .views import (
    home, register, user_login, user_logout, dashboard,
    process_image_feed, add_image_feed, delete_image,
    password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'object_detection'

urlpatterns = [
                  path('', home, name='home'),  # Главная страница
                  path('register/', register, name='register'),  # Страница регистрации
                  path('login/', user_login, name='login'),  # Страница входа
                  path('logout/', user_logout, name='logout'),  # Выход из аккаунта
                  path('dashboard/', dashboard, name='dashboard'),  # Личный кабинет
                  path('process/<int:feed_id>/', process_image_feed, name='process_feed'),  # Обработка изображения
                  path('add-image-feed/', add_image_feed, name='add_image_feed'),  # Добавление изображения
                  path('image/delete/<int:image_id>/', delete_image, name='delete_image'),  # Удаление изображения
                  path('password_reset/', password_reset, name='password_reset'),  # Сброс пароля
                  path('password_reset_done/', password_reset_done, name='password_reset_done'),
                  # Завершение сброса пароля
                  path('password_reset_confirm/', password_reset_confirm, name='password_reset_confirm'),
                  # Подтверждение сброса пароля
                  path('reset/done/', password_reset_complete, name='password_reset_complete'),
                  # Завершение процесса сброса пароля
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

object_detection/models.py
from django.db import models
from django.conf import settings
import os


# Модель ImageFeed представляет загруженные пользователем изображения
class ImageFeed(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)  # Пользователь, загрузивший изображение
    image = models.ImageField(upload_to='images/')  # Оригинальное изображение
    processed_image = models.ImageField(upload_to='processed_images/', null=True,
                                        blank=True)  # Обработанное изображение

    def __str__(self):
        return f"{self.user.username} - {self.image.name}"

    def delete(self, *args, **kwargs):
        # Удаление связанных файлов при удалении объекта
        if self.image and os.path.isfile(self.image.path):
            os.remove(self.image.path)
        if self.processed_image and os.path.isfile(self.processed_image.path):
            os.remove(self.processed_image.path)
        super().delete(*args, **kwargs)


# Модель DetectedObject представляет распознанные объекты в изображении
class DetectedObject(models.Model):
    image_feed = models.ForeignKey(ImageFeed, related_name='detected_objects',
                                   on_delete=models.CASCADE)  # Связь с ImageFeed
    object_type = models.CharField(max_length=100)  # Тип объекта (например, 'person', 'dog')
    confidence = models.FloatField()  # Уверенность модели в правильности распознавания
    location = models.CharField(max_length=255)  # Координаты объекта на изображении

    def __str__(self):
        return f"{self.object_type} ({self.confidence * 100}%) on {self.image_feed.image.name}"


# Модель DescribedImage представляет описание изображения
class DescribedImage(models.Model):
    image_feed = models.ForeignKey(ImageFeed, related_name='described_image',
                                   on_delete=models.CASCADE)  # Связь с ImageFeed
    describe = models.CharField(max_length=100)  # Описание изображения

    def __str__(self):
        return f"{self.describe}"

object_detection/forms.py
from django import forms
from .models import ImageFeed
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Форма для загрузки изображения
class ImageFeedForm(forms.ModelForm):
    image = forms.ImageField(label='', widget=forms.FileInput(attrs={'accept': 'image/*'}))  # Поле для загрузки изображения

    class Meta:
        model = ImageFeed
        fields = ['image']

# Кастомизированная форма регистрации пользователя
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()  # Добавление поля email к стандартной форме

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

object_detection/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from .models import ImageFeed, DetectedObject, DescribedImage
from .utils import process_image
from .forms import ImageFeedForm, CustomUserCreationForm


# Главная страница
def home(request):
    return render(request, 'object_detection/home.html')


# Регистрация нового пользователя
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('object_detection:dashboard')
    else:
        form = CustomUserCreationForm()
    return render(request, 'object_detection/register.html', {'form': form})


# Вход пользователя
def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('object_detection:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'object_detection/login.html', {'form': form})


# Выход пользователя (доступно только авторизованным пользователям)
@login_required
def user_logout(request):
    logout(request)
    return redirect('object_detection:login')


# Личный кабинет (доступно только авторизованным пользователям)
@login_required
def dashboard(request):
    image_feeds = ImageFeed.objects.filter(user=request.user)
    detected_objects = DetectedObject.objects.filter(image_feed__in=image_feeds)
    describe_images = DescribedImage.objects.filter(image_feed__in=image_feeds)
    return render(request, 'object_detection/dashboard.html', {
        'image_feeds': image_feeds,
        'detected_objects': detected_objects,
        'describe_images': describe_images
    })


# Обработка изображения (доступно только авторизованным пользователям)
@login_required
def process_image_feed(request, feed_id):
    image_feed = get_object_or_404(ImageFeed, id=feed_id)
    model_type = request.POST.get('model_type', 'model_1')
    success = process_image(image_feed.id, model_type)
    if success:
        return redirect('object_detection:dashboard')
    else:
        return redirect('object_detection:dashboard')


# Добавление нового изображения (доступно только авторизованным пользователям)
@login_required
def add_image_feed(request):
    if request.method == 'POST':
        form = ImageFeedForm(request.POST, request.FILES)
        if form.is_valid():
            image_feed = form.save(commit=False)
            image_feed.user = request.user
            image_feed.save()
            return redirect('object_detection:dashboard')
    else:
        form = ImageFeedForm()
    return render(request, 'object_detection/add_image_feed.html', {'form': form})


# Удаление изображения (доступно только авторизованным пользователям)
@login_required
def delete_image(request, image_id):
    image = get_object_or_404(ImageFeed, id=image_id, user=request.user)
    image.delete()
    return redirect('object_detection:dashboard')


# Сброс пароля (начало процесса)
def password_reset(request):
    if request.method == 'POST':
        form = auth_views.PasswordResetForm(request.POST)
        if form.is_valid():
            form.save(
                request=request,
                use_https=request.is_secure(),
                email_template_name='object_detection/password_reset_email.html',
                subject_template_name='object_detection/password_reset_subject.txt'
            )
            return redirect('object_detection:password_reset_done')
    else:
        form = auth_views.PasswordResetForm()
    return render(request, 'object_detection/password_reset.html', {'form': form})


# Завершение сброса пароля
def password_reset_done(request):
    return render(request, 'object_detection/password_reset_done.html')


# Подтверждение сброса пароля
def password_reset_confirm(request, uidb64=None, token=None):
    return render(request, 'object_detection/password_reset_confirm.html')


# Завершение процесса сброса пароля
def password_reset_complete(request):
    return render(request, 'object_detection/password_reset_complete.html')

object_detection/templates/object_detection/add_image_feed.html
{% extends "object_detection/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Загрузка изображений</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn btn-primary">Загрузить изображение</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

object_detection/templates/object_detection/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Платформа Распознавания Объектов{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <style>
        body {
            background-color: #f8f9fa;
            font-size: 16px; /* Основной размер шрифта */
        }
        .sidebar {
            height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
            width: 250px;
            background-color: #6c757d;
            color: #fff;
            padding: 15px;
            box-shadow: 2px 0 5px rgba(0,0,0,0.1);
            font-size: 1rem; /* Размер шрифта */
        }
        .sidebar h3 {
            color: #ffffff; /* Цвет текста */
            text-align: center; /* Выравнивание текста по центру */
            margin-bottom: 20px; /* Отступ снизу */
            font-size: 1.5rem; /* Размер шрифта */
        }
        .sidebar img {
            max-width: 100%;
            height: auto;
            margin-bottom: 15px;
            border: 2px solid #fff;
            box-shadow: 0 0 10px rgba(0,0,0,0.5);
        }
        .sidebar .nav-link {
            color: #fff;
            margin: 5px 0;
            padding: 10px;
            border: 1px solid transparent;
            border-radius: 5px;
            transition: background-color 0.3s, border-color 0.3s;
            font-size: 1rem; /* Размер шрифта */
        }
        .sidebar .nav-link:hover, .sidebar .nav-link.active {
            background-color: #495057;
            border-color: #007bff;
        }
        .main-content {
            margin-left: 270px;
            padding: 15px;
            background: url("{% static 'background.jpg' %}") no-repeat center center fixed;
            background-size: cover;
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            flex-wrap: wrap;
            color: #343a40;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
            font-size: 1rem; /* Размер шрифта */
        }
        .content-container {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 60px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            width: 100%; /* Ширина контейнера */
            max-width: 800px; /* Максимальная ширина контейнера */
            margin: auto; /* Центрирование контейнера */
            font-size: 1rem; /* Размер шрифта */
        }
        h1 {
            font-size: 2.5rem; /* Размер шрифта для h1 */
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        h2 {
            font-size: 2rem; /* Размер шрифта для h2 */
            font-weight: bold;
            text-align: left;
            margin-bottom: 20px;
        }
        p {
            font-size: 1.5rem; /* Размер шрифта для p */
            text-align: center;
        }
        p2 {
            font-size: 1.5rem; /* Размер шрифта для p2 */
            text-align: left;
        }
        .custom-form p {
            font-size: 0.875rem; /* Размер шрифта для формы */
            text-align: left;
        }
        header {
            background-color: #343a40;
            padding: 10px 0;
        }
        header .navbar-brand, header .nav-link {
            color: #fff !important;
        }
        .card-header, .btn-primary {
            background-color: #007bff;
            color: #fff;
        }
        .btn-secondary {
            background-color: #6c757d;
            color: #fff;
        }
        .btn-danger {
            background-color: #dc3545;
            color: #fff;
        }
        .centered-link {
            text-align: center;
            font-size: 1.5rem;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .btn-yellow {
            color: yellow;
            font-size: 1rem;
            padding-left: 10px;
        }
        .card-body {
            font-size: 1rem; /* Размер шрифта */
        }
        .btn {
            font-size: 1rem; /* Размер шрифта кнопок */
        }
        .card {
            margin-bottom: 20px;
        }
        .loader {
            border: 8px solid #f3f3f3;
            border-top: 8px solid #3498db;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 2s linear infinite;
            display: inline-block;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    </style>
</head>
<body>
<div class="sidebar">
    <h3>Платформа Распознавания Объектов "ПРО"</h3>
    <img src="{% static 'logo2.jpg' %}" alt="Logo">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'object_detection:home' %}">Главная</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'object_detection:dashboard' %}">Дашборд</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'object_detection:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'object_detection:login' %}">Войти</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'object_detection:register' %}">Зарегистрироваться</a>
        </li>
        {% endif %}
    </ul>
</div>

<main class="main-content">
    <div class="content-container">
        {% block content %}
        {% endblock %}
    </div>
</main>

<!-- Подключение Bootstrap и других зависимостей -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
<script src="{% static 'object_detection/loader.js' %}?v={{ STATIC_VERSION }}"></script>
</body>
</html>

object_detection/templates/object_detection/dashboard.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2 class="mb-4">Дашборд</h2>
<a href="{% url 'object_detection:add_image_feed' %}" class="btn btn-primary mb-3">Добавить изображение</a>
{% load static %}
{% load custom_filters %}

<div class="row">
    {% for feed in image_feeds %}
    <div class="col-md-6">
        <div class="card mb-3">
            <div class="card-body">
                <!-- Форма для выбора модели и обработки изображения -->
                <form action="{% url 'object_detection:process_feed' feed.id %}" method="post"
                      class="d-inline process-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="model_type_{{ feed.id }}">Выбрать модель</label>
                        <select name="model_type" id="model_type_{{ feed.id }}" class="form-control">
                            <option value="model_1">Объекты на изображении</option>
                            <option value="model_2">Описание изображения</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-secondary process-button">Обработать</button>
                    <div class="loader" style="display: none;"></div>
                </form>
                <!-- Ссылки на оригинальное и обработанное изображения -->
                <a href="{{ feed.image.url }}" target="_blank">
                    <img src="{{ feed.image.url }}" alt="Original Image" class="img-thumbnail"
                         style="width: 50px; height: 50px;">
                </a>
                {% if feed.processed_image %}
                <a href="{{ feed.processed_image.url }}" target="_blank">
                    <img src="{{ feed.processed_image.url }}" alt="Processed Image" class="img-thumbnail"
                         style="width: 50px; height: 50px;">
                </a>
                {% endif %}
                <!-- Список распознанных объектов и описаний изображения -->
                <ul>
                    {% for obj in detected_objects %}
                    {% if obj.image_feed.id == feed.id %}
                    <li>{{ obj.object_type }} ({{ obj.confidence|to_percentage }})</li>
                    {% endif %}
                    {% endfor %}
                    {% for desc in describe_images %}
                    {% if desc.image_feed.id == feed.id %}
                    <li>{{ desc.describe }}</li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <!-- Кнопка для удаления изображения -->
            <div class="card-footer">
                <form action="{% url 'object_detection:delete_image' feed.id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

<script src="{% static 'object_detection/loader.js' %}?v={{ STATIC_VERSION }}"></script>

object_detection/templates/object_detection/home.html
{% extends "object_detection/base.html" %}

{% block content %}
<h1>Добро пожаловать на платформу распознавания объектов "ПРО"</h1>
<p>Это полнофункциональное приложение для выполнения задач по обнаружению объектов на изображениях</p>
<div class="centered-link">
    <a href="{% url 'object_detection:dashboard' %}">Ваш дашборд</a>
</div>
{% endblock %}

object_detection/templates/object_detection/login.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Вход</h2>
<!-- Форма входа пользователя -->
<form method="post" class="my-4 custom-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-2">Войти</button>
</form>
<div class="custom-form p">
    <p><a href="{% url 'object_detection:register' %}">Зарегистрироваться</a></p>
    <p><a href="{% url 'object_detection:password_reset' %}">Забыли пароль?</a></p>
</div>
{% endblock %}

object_detection/templates/object_detection/password_reset.html
{% extends "object_detection/base.html" %}
{% block content %}
<h2>Сброс пароля</h2>
<form method="post" class="my-4 custom-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-2">Отправить</button>
</form>
{% endblock %}

object_detection/templates/object_detection/password_reset_complete.html
{% extends "object_detection/base.html" %}
{% block content %}
<h2>Пароль успешно сброшен</h2>
<p>Ваш пароль был успешно сброшен. Теперь вы можете <a href="{% url 'object_detection:login' %}">войти</a> с новым паролем.</p>
{% endblock %}

object_detection/templates/object_detection/password_reset_confirm.html
{% extends "object_detection/base.html" %}
{% block content %}
<h2>Введите новый пароль</h2>
<form method="post" class="my-4 custom-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-2">Сбросить пароль</button>
</form>
{% endblock %}

object_detection/templates/object_detection/password_reset_done.html
{% extends "object_detection/base.html" %}
{% block content %}
<h2>Письмо для сброса пароля отправлено</h2>
<p>Пожалуйста, проверьте вашу почту для получения дальнейших инструкций.</p>
{% endblock %}

object_detection/templates/object_detection/password_reset_email.html
<p>Для сброса пароля перейдите по следующей ссылке:</p>
<p><a href="{{ protocol }}://{{ domain }}{% url 'object_detection:password_reset_confirm' %}">Сбросить пароль</a></p>

object_detection/templates/object_detection/register.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Регистрация пользователя</h2>
<!-- Форма регистрации нового пользователя -->
<form method="post" class="my-4 custom-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-2">Зарегистрироваться</button>
</form>
<a href="{% url 'object_detection:login' %}">Войти</a>
{% endblock %}